architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/${rootProject.archives_name}.accesswidener")
}

repositories {
    maven {
        name = "Cobbled Creators"
        url = "https://maven.cobbled-creators.org/releases/"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "com.cobblemon:mod:$rootProject.cobblemon_version"
    modApi "com.bedrockk:molang:1.1.20"
    modCompileOnly(libs.graal.core)
    modCompileOnly(files "lib/asymmetricbattles-fabric-${rootProject.asymmetricbattles_version}.jar")
    include(modApi "me.shedaniel.cloth:cloth-config:$rootProject.cloth_config_version")
}